PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE characters ( id INTEGER PRIMARY KEY, name TEXT NOT NULL , ability_score_set_id integer NOT NULL, alignment_order text not null, alignment_morality text not null, FOREIGN KEY(ability_score_set_id) references ability_score_sets(id));
INSERT INTO "characters" VALUES(1,'IDRIGOTH',1,'neutral','good');
INSERT INTO "characters" VALUES(2,'Vor',2,'chaotic','good');
INSERT INTO "characters" VALUES(3,'Ardo',3,'neutral','good');
CREATE TABLE ability_score_sets (id integer primary key, str integer not null, dex integer not null, con integer not null, int integer not null, wis integer not null, cha integer not null);
INSERT INTO "ability_score_sets" VALUES(1,12,15,18,14,10,8);
INSERT INTO "ability_score_sets" VALUES(2,10,18,10,14,10,10);
INSERT INTO "ability_score_sets" VALUES(3,8,15,10,14,10,18);
COMMIT;
